{
  "formatVersion": "1.1",
  "component": {
    "group": "com.morayl",
    "module": "footprint-ktx",
    "version": "1.2.0.alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0.alpha1.aar",
          "url": "footprint-ktx-1.2.0.alpha1.aar",
          "size": 10955,
          "sha512": "bcb74d457304141e1b300d6ec5027f03fbf3ec1e3640a520b46d24a78cf7aff06a6bf205d97dd87f0f8da5d27ac261b63cbfd2036e5631fc9389654a04af0e43",
          "sha256": "946778ca940db586dfbfe0d9814af0ffdb5cec093f09a29665b1b3c8f54c5920",
          "sha1": "6c0871e81cca99f9500c95ae394c8ce3a6d67f57",
          "md5": "35cae4b02014ee60dc243cb7805214e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "footprint-ktx-1.2.0.alpha1.aar",
          "url": "footprint-ktx-1.2.0.alpha1.aar",
          "size": 10955,
          "sha512": "bcb74d457304141e1b300d6ec5027f03fbf3ec1e3640a520b46d24a78cf7aff06a6bf205d97dd87f0f8da5d27ac261b63cbfd2036e5631fc9389654a04af0e43",
          "sha256": "946778ca940db586dfbfe0d9814af0ffdb5cec093f09a29665b1b3c8f54c5920",
          "sha1": "6c0871e81cca99f9500c95ae394c8ce3a6d67f57",
          "md5": "35cae4b02014ee60dc243cb7805214e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0.alpha1-sources.jar",
          "url": "footprint-ktx-1.2.0.alpha1-sources.jar",
          "size": 4115,
          "sha512": "b12266ddaaaff1cf921116cd274d749d876ed86aa1a5f14e2059f6479863dd7a740f354bbfe708ad44e76ad8036cf1ebb155fc1ed0637a91811c478f7e479a08",
          "sha256": "2740ca4715d7ec4dcf285d7b0f0f412fc7a409f1155a660108f9d05d643789fd",
          "sha1": "765928f4d04c96e1fe622378dfd6c5244948381c",
          "md5": "a05bc2e4b8f832ad1c0650fc7ce34c5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0.alpha1-javadoc.jar",
          "url": "footprint-ktx-1.2.0.alpha1-javadoc.jar",
          "size": 289582,
          "sha512": "ce2e06dae4e6c1292530928f8610af4bb01db0ddf721858a5815f6030402494521f03dfb8a42605ab8c59f5122d98bcca331e0505b9cd04e772bd586c99d8a00",
          "sha256": "bbac8d0a7603cae0975acda91c2f7ce0b15c1e38fd9363ca759ced306499174b",
          "sha1": "cd521e091741b7f70f76e52c6bdf12e86bd649ae",
          "md5": "81c20a86912ea7c5f295dc3c9af12d03"
        }
      ]
    }
  ]
}
