{
  "formatVersion": "1.1",
  "component": {
    "group": "com.morayl",
    "module": "footprint-ktx",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0.aar",
          "url": "footprint-ktx-1.2.0.aar",
          "size": 14266,
          "sha512": "1e943582efc8cb29c4dd899b5168d9074ccc2d33b3953060c9aa514c92e531c05bc855e8cb372a921d0331dfb692896992756b242602d298732e35e9d6d0b2c3",
          "sha256": "cbff5ef9f113a583860d27c818b14c6114e1fa07d881e9eb6cd2a2da690b8874",
          "sha1": "aedcda793ecf0fe0ea23e0bcf0d3fe60f9431e6b",
          "md5": "d7cc46432c1547cd536e0e7cce97b581"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "footprint-ktx-1.2.0.aar",
          "url": "footprint-ktx-1.2.0.aar",
          "size": 14266,
          "sha512": "1e943582efc8cb29c4dd899b5168d9074ccc2d33b3953060c9aa514c92e531c05bc855e8cb372a921d0331dfb692896992756b242602d298732e35e9d6d0b2c3",
          "sha256": "cbff5ef9f113a583860d27c818b14c6114e1fa07d881e9eb6cd2a2da690b8874",
          "sha1": "aedcda793ecf0fe0ea23e0bcf0d3fe60f9431e6b",
          "md5": "d7cc46432c1547cd536e0e7cce97b581"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0-sources.jar",
          "url": "footprint-ktx-1.2.0-sources.jar",
          "size": 4545,
          "sha512": "84b48e2c519fc8e2862e5e2e781a5c738c0cb98e67d5bf2e784d22160bbb6c4369b77a11110657767a61ed17d1199d44613b19c1be171abff1ca67c2a947ff6c",
          "sha256": "b2c77868f09b1349cb9957247283ae95549cda52d5965d5a0fdc89c7e6914c5f",
          "sha1": "7d0ea1080552b3cff1dc1e6bcab86dd673d08450",
          "md5": "3da1fe775ad1da2fb26d07d44b0b4aa3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "footprint-ktx-1.2.0-javadoc.jar",
          "url": "footprint-ktx-1.2.0-javadoc.jar",
          "size": 289735,
          "sha512": "e4155f8f2237d24319e1be892e3f5c86258e499ae4fd5eeea43ff0af070421fc4d006d1df21b9004a9aad4466d3447505c872bfe062e5a8b13c6002f8cdf8464",
          "sha256": "418841c18fa92c1737bdf76a78543ac818b44d1954ab34153be62d51060c4a7e",
          "sha1": "80b034fd99ef544f687d6dc40d3be66e0a200ec4",
          "md5": "57a061746c2f24a1cac01375af3b598f"
        }
      ]
    }
  ]
}
